name: "webapp"

services:
  webapp:
      build:
        context: .
        dockerfile: ./docker/DockerFile
        args:
          WWW_USER_ID: "${WWW_USER_ID:-1000}"
          WWW_GROUP_ID: "${WWW_GROUP_ID:-1000}"
      ports:
        - "80:80"
        - "8080:8080"
      volumes:
        - ./src/backend/:/var/www/webapp/backend
        - ./src/frontend/:/var/www/webapp/frontend
      extra_hosts:
        - "backend.test:127.0.0.1"
        - "frontend.test:127.0.0.1"
      networks:
        - webapp
      depends_on:
        - mariadb
      command: bash -c "/usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf"

  mariadb:
      image: mariadb:10.1
      volumes:
        - mariadb_data:/var/lib/mysql
        - ./docker-dev/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
      networks:
        - webapp
      ports:
        - "3306:3306"
      environment:
        MYSQL_USER: "app"
        MYSQL_PASSWORD: "app"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

networks:
  webapp:
    external: true

volumes:
  mariadb_data:
    external: false
